// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw85uRM-aZr3ZZDj3YVEEx0xoUZVR82FQ',
    appId: '1:539912648822:web:01bdfb9b1fe4cafe054757',
    messagingSenderId: '539912648822',
    projectId: 'chatgpt-15631',
    authDomain: 'chatgpt-15631.firebaseapp.com',
    storageBucket: 'chatgpt-15631.appspot.com',
    measurementId: 'G-0BJEQY8186',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIdYFHGzQ7VaZumEnX8jQ2wvVVEKu84H4',
    appId: '1:539912648822:android:36ec6107f1daf489054757',
    messagingSenderId: '539912648822',
    projectId: 'chatgpt-15631',
    storageBucket: 'chatgpt-15631.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh06kgl9mWmz7URXRqgZBl5qHxI4SA9ho',
    appId: '1:539912648822:ios:c07311096ed58d7d054757',
    messagingSenderId: '539912648822',
    projectId: 'chatgpt-15631',
    storageBucket: 'chatgpt-15631.appspot.com',
    iosClientId: '539912648822-d9bh3egnkm56af7egjr7rb6bac9dide3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh06kgl9mWmz7URXRqgZBl5qHxI4SA9ho',
    appId: '1:539912648822:ios:c07311096ed58d7d054757',
    messagingSenderId: '539912648822',
    projectId: 'chatgpt-15631',
    storageBucket: 'chatgpt-15631.appspot.com',
    iosClientId: '539912648822-d9bh3egnkm56af7egjr7rb6bac9dide3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatgpt',
  );
}
