class Autogenerated {
  String? id;
  String? object;
  int? created;
  String? ownedBy;
  String? root;

  Autogenerated(
      {this.id,
      this.object,
      this.created,
      this.ownedBy,
      this.root,});

  factory Autogenerated.fromJson(Map<String, dynamic> json) => Autogenerated(
    id : json["id"] as String,
    object : json["object"] as String,
    created : json["created"] as int,
    ownedBy : json["owned_by"] as String ,
    root : json["root"] as String ,
  );

  Map<String, dynamic> toJson() => {
    'id' : id,
    'object' : object,
    'created' : created,
    'owned_by' : ownedBy,
    'root' : root,
  };
}
 