import 'package:logger/logger.dart';
import '../../../feature/model/app_response.dart';
import '../../../feature/model/autogenerated_model.dart';
import '../../utils/constance_network.dart';
import '../feature/home_feature.dart';

class HomeHelper {
  HomeHelper._internal();
  static final HomeHelper instance = HomeHelper._internal();

  Future<List<Autogenerated>> getModelss() async {
    try {
      AppResponse res = await HomeFeature.getInstance.getModels(
        url: ConstanceNetwork.models,
        header: ConstanceNetwork.header(TypeToken.authorization),
      );
      return res.data
          .map<Autogenerated>((e) => Autogenerated.fromJson(e))
          .toList();
    } catch (e) {
      Logger().e(e.toString());
      return [];
    }
  }
}
